package malilib.util.nbt;

/**
 * NBT Tag Constants Library --
 * This is meant to help keep track of NBT Key changes across Minecraft; and to use them while parsing NBT tags.
 */
public class NbtKeys
{
	// Generic
	public static final String ID                       = "id";                     // Entity, Tile Entity, Items, etc
	public static final String POS                      = "Pos";                    // Entity (List, Double)
	public static final String CUSTOM_NAME              = "CustomName";             // Tile Entity / Entity (Str)
	public static final String COLOR                    = "Color";                  // Banner Pattern, Shulker, Sign, Sheep (Byte) --> DyeColor
	public static final String UUID                     = "UUID";                   // All Over the place
	public static final String UUID_MOST                = "UUIDMost";               // UUID (Most)
	public static final String UUID_LEAST               = "UUIDLeast";              // UUID (Least)

	// Inventory
	public static final String ITEMS                    = "Items";                  // Brewing Stand, Furnace, Chest, Disp/Drop, Hopper, Shulker, Minecart, ChestedHorse, etc.
	public static final String INVENTORY                = "Inventory";              // Player, Villager, Zombified Pigmen, Pillagers, etc. (List, Comp) -> Slotted ItemStacks
	public static final String SLOT                     = "Slot";                   // Any Slotted Inventory
	public static final String ITEM                     = "Item";                   // Flower Pot, ItemEntity, Item Frame (Single Item Inventory)
	public static final String LOOT_TABLE               = "LootTable";              // Lootable Container (Str)
	public static final String LOOT_TABLE_SEED          = "LootTableSeed";          // Lootable Container (Long)

	// Item Tags General
	public static final String COUNT                    = "Count";                  // ItemStack (Byte)
	public static final String DAMAGE                   = "Damage";                 // ItemStack (Short)
	public static final String TAG                      = "tag";                    // ItemStack (Comp)
	public static final String ENCHANTMENTS             = "ench";                   // ItemStack (List, Comp) -->
	public static final String ENCH_ID                  = "id";                     // ItemStack, Ench (Short) --> Enchantment
	public static final String ENCH_LEVEL               = "lvl";                    // ItemStack, Ench (Short)
	public static final String DISPLAY                  = "display";                // ItemStack (Comp) -->
	public static final String DISP_NAME                = "Name";                   // display (Str)
	public static final String DISP_LOC_NAME            = "LocName";                // display (Str)
	public static final String DISP_COLOR               = "color";                  // display (Int)
	public static final String DISP_LORE                = "Lore";                   // display (List, Str) --> Text
	public static final String DISP_MAP_COLOR           = "MapColor";               // display (Int)
	public static final String HIDE_FLAGS               = "HideFlags";              // ItemStack (Int)
	public static final String UNBREAKABLE              = "Unbreakable";            // ItemStack (Bool)
	public static final String REPAIR_COST              = "RepairCost";             // ItemStack (Int)
	public static final String CAN_DESTROY              = "CanDestroy";             // ItemStack (List, Str) --> Block
	public static final String CAN_PLACE_ON             = "CanPlaceOn";             // ItemStack (List, Str) --> Block
	public static final String ATTRIBUTE_MODIFIERS      = "AttributeModifiers";     // ItemStack (List, Comp) --> AttributeModifier
	public static final String ATTRIBUTE_NAME           = "AttributeName";          // ItemStack, AttribMod (Str)
	public static final String ATTRIBUTE_SLOT           = "Slot";                   // ItemStack, AttribMod (Str)
	public static final String ATTR_MOD_NAME            = "Name";                   // ItemStack, AttribMod (Str)
	public static final String ATTR_MOD_AMOUNT          = "Amount";                 // ItemStack, AttribMod (Double)
	public static final String ATTR_MOD_OPERATION       = "Operation";              // ItemStack, AttribMod (Int)
	public static final String ATTR_MOD_UUID            = "UUID";                   // ItemStack, AttribMod (UUID)
	public static final String BLOCK_ENTITY             = "BlockEntityTag";         // ItemStack (Comp)

	// Item Tags Specific
	public static final String ITEM_SKULL_OWNER         = "SkullOwner";              // Skull (Str) --> GameProfile
	public static final String MAP_SCALE_DIR            = "map_scale_direction";     // Map (Int)
	public static final String MAP_TRACKING_POS         = "map_tracking_position";   // Map (Bool)
	public static final String MAP_DECORATIONS          = "Decorations";             // Map (List, Comp)
	public static final String MAP_DECO_TYPE            = "type";                    // Map, Deco (Byte)
	public static final String MAP_DECO_ID              = "id";                      // Map, Deco (Str)
	public static final String MAP_DECO_X               = "x";                       // Map, Deco (Double)
	public static final String MAP_DECO_Z               = "z";                       // Map, Deco (Double)
	public static final String MAP_DECO_ROT             = "rot";                     // Map, Deco (Double)
	public static final String STORED_ENCHANTMENTS      = "StoredEnchantments";      // Enchanted Book (List, Comp)
	public static final String FIREWORKS                = "Fireworks";               // Firework (Comp)
	public static final String FW_FLIGHT                = "Flight";                  // Firework (Byte)
	public static final String FW_EXPLOSIONS            = "Explosions";              // Firework (List, Comp)
	public static final String FW_EXPLOSION             = "Explosion";               // Firework Charge (Comp)
	public static final String FW_EXP_TYPE              = "Type";                    // Firework Charge (Byte)
	public static final String FW_EXP_COLORS            = "Colors";                  // Firework Charge (Int Array)
	public static final String FW_EXP_FADE_COLORS       = "FadeColors";              // Firework Charge (Int Array)
	public static final String FW_EXP_TRAIL             = "Trail";                   // Firework Charge (Bool)
	public static final String FW_EXP_FLICKER           = "Flicker";                 // Firework Charge (Bool)
	public static final String BOOK_RECIPES             = "Recipes";                 // KnowledgeBook (List, Str) -> Recipe
	public static final String ENTITY_TAG               = "EntityTag";               // SpawnEgg (Comp)
	public static final String BOOK_PAGES               = "pages";                   // WritableBook (List, Str)
	public static final String BOOK_AUTHOR              = "author";                  // WrittenBook (Str)
	public static final String BOOK_RESOLVED            = "resolved";                // WrittenBook (Bool)

	// Tile/Block Entity
	public static final String TE_POS_X                 = "x";                      // [Base] (Int)
	public static final String TE_POS_Y                 = "y";                      // [Base] (Int)
	public static final String TE_POS_Z                 = "z";                      // [Base] (Int)
	public static final String LOCK                     = "Lock";                   // Lockable Container (Str)
	public static final String BASE_COLOR               = "Base";                   // Banner (Int)
	public static final String PATTERNS                 = "Patterns";               // Banner (LIST: Color, Pattern)
	public static final String PATTERN                  = "Pattern";                // Banner, Pattern
	public static final String PRIMARY_EFFECT           = "Primary";                // Beacon (Int)
	public static final String SECONDARY_EFFECT         = "Secondary";              // Beacon (Int)
	public static final String LEVELS                   = "Levels";                 // Beacon (Int)
	public static final String BED_COLOR                = "color";                  // Dye Color (Int)
	public static final String BREW_TIME                = "BrewTime";               // Bewing Stand (Short)
	public static final String FUEL                     = "Fuel";                   // Brewing Stand (Byte)
	public static final String OUTPUT_SIGNAL            = "OutputSignal";           // Comparator (Int)
	public static final String PORTAL_AGE               = "Age";                    // End Gateway (Long)
	public static final String EXIT_PORTAL              = "ExitPortal";             // End Gateway (Comp/Pos)
	public static final String EXACT_TELEPORT           = "ExactTeleport";          // End Gateway (Bool)
	public static final String POT_DATA                 = "Data";                   // Flower Pot (Int)
	public static final String BURN_TIME                = "BurnTime";               // Furnace (Short)
	public static final String COOK_TIME_SPENT          = "CookTime";               // Furnace (Short)
	public static final String COOK_TIME_TOTAL          = "CookTimeTotal";          // Furnace (Short)
	public static final String RECIPES_USED_SIZE        = "RecipesUsedSize";        // Furnace (Short)
	public static final String RECIPE_LOCATION_PREFIX   = "RecipeLocation";         // Furnace (Str)
	public static final String RECIPE_AMOUNT_PREFIX     = "RecipeAmount";           // Furnace (Int)
	public static final String TRANSFER_COOLDOWN        = "TransferCooldown";       // Hopper, Hopper MC (Int)
	public static final String NOTE                     = "note";                   // Note Block (Byte)
	public static final String SIGN_TEXT_PREFIX         = "Text";                   // Sign (Str)
	public static final String SIGN_FILTER_PREFIX       = "FilteredText";           // Sign (Str)
	public static final String SIGN_GLOWING             = "GlowingText";            // Sign (Bool)
	public static final String COMMAND_STATS            = "CommandStats";           // Sign (Compound, Dumb)
	public static final String RECORD_ITEM              = "RecordItem";             // Jukebox (Comp) --> ItemStack (Single Item Inventory)
	public static final String RECORD                   = "Record";                 // Jukebox (Int) --> ItemStack (By Item ID)

	// Command Block, (Minecart also)
	public static final String POWERED                  = "powered";                // Command, Note Block, Creeper (Bool)
	public static final String COND_MET                 = "conditionMet";           // Bool
	public static final String AUTO                     = "auto";                   // Bool
	public static final String COMMAND                  = "Command";                // Str
	public static final String SUCCESS_COUNT            = "SuccessCount";           // Int
	public static final String TRACK_OUTPUT             = "TrackOutput";            // Bool
	public static final String LAST_OUTPUT              = "LastOutput";             // Str
	public static final String UPD_LAST_EXEC            = "UpdateLastExecution";    // Bool
	public static final String LAST_EXEC                = "LastExecution";          // Long

	// Monster Spawner, (Minecart also)
	public static final String SPAWN_POTENTIALS         = "SpawnPotentials";        // (List, Compound)
	public static final String SPAWN_ID                 = "id";                     // (Potentials, Str)
	public static final String SPAWN_ENTITY             = "Entity";                 // (Potentials, Compound)
	public static final String SPAWN_WEIGHT             = "Weight";                 // (Potentials, Int)
	public static final String SPAWN_DATA               = "SpawnData";              // Compound
	public static final String SPAWN_DELAY              = "Delay";                  // Short
	public static final String MIN_SPAWN_DELAY          = "MinSpawnDelay";          // (Numeric, Short)
	public static final String MAX_SPAWN_DELAY          = "MaxSpawnDelay";          // Short
	public static final String SPAWN_COUNT              = "SpawnCount";             // Short
	public static final String MAX_NEARBY_ENT           = "MaxNearbyEntities";      // (Numeric, Short)
	public static final String REQ_PLAYER_RANGE         = "RequiredPlayerRange";    // Short
	public static final String SPAWN_RANGE              = "SpawnRange";             // (Numeric, Short)

	// Piston
	public static final String BLOCK_ID                 = "blockId";                // Int
	public static final String BLOCK_DATA               = "blockData";              // Int
	public static final String FACING                   = "facing";                 // Int
	public static final String PROGRESS                 = "progress";               // Float
	public static final String EXTENDING                = "extending";              // Bool
	public static final String SOURCE                   = "source";                 // Bool

	// Skull
	public static final String SKULL_TYPE               = "SkullType";              // Skull (Byte)
	public static final String SKULL_ROT                = "Rot";                    // Skull (Byte)
	public static final String SKULL_OWNER              = "Owner";                  // Skull (Comp, Game Profile)
	public static final String SKULL_EXTRA_TYPE         = "ExtraType";              // Skull (Str, Game Profile Name)
	public static final String PROFILE_NAME             = "Name";                   // Profile (Str)
	public static final String PROFILE_ID               = "Id";                     // Profile (Str)
	public static final String PROFILE_PROPS            = "Properties";             // Profile (Compound) -> (Keyed List)
	public static final String PROFILE_VALUE            = "Value";                  // Profile, Properties List (Str)
	public static final String PROFILE_SIGNATURE        = "Signature";              // Profile, Properties List (Str)

	// Entity [Base]
	public static final String MOTION                   = "Motion";                 // [Base] Double List
	public static final String ROTATION                 = "Rotation";               // [Base] Float List
	public static final String FALL_DISTANCE            = "FallDistance";           // [Base] Float
	public static final String FIRE                     = "Fire";                   // [Base] Short
	public static final String AIR                      = "Air";                    // [Base] Short
	public static final String ON_GROUND                = "OnGround";               // [Base] Bool
	public static final String DIMENSION                = "Dimension";              // [Base] Int
	public static final String INVULNERABLE             = "Invulnerable";           // [Base] Bool
	public static final String PORTAL_COOLDOWN          = "PortalCooldown";         // [Base] Int
	public static final String CUSTOM_NAME_VISIBLE      = "CustomNameVisible";      // [Base] Bool
	public static final String SILENT                   = "Silent";                 // [Base] Bool
	public static final String NO_GRAVITY               = "NoGravity";              // [Base] Bool
	public static final String GLOWING                  = "Glowing";                // [Base] Bool
	public static final String COMMAND_TAGS             = "Tags";                   // [Base] String List
	public static final String PASSENGERS               = "Passengers";             // [Base] Compound List (Entity NBT)
	public static final String AGE                      = "Age";                    // ItemEntity, XP (Short)
	public static final String ITEM_HEALTH              = "Health";                 // ItemEntity, XP (Short)
	public static final String PICKUP_DELAY             = "PickupDelay";            // ItemEntity (Short)
	public static final String THROWER                  = "Thrower";                // ItemEntity (Str)
	public static final String OWNER                    = "Owner";                  // ItemEntity (Str)
	public static final String FUSE                     = "Fuse";                   // TNT Primed, Creeper (Short)
	public static final String FANGS_WARMUP             = "Warmup";                 // Fangs (Int)
	public static final String FANGS_OWNER              = "OwnerUUID";              // Fangs, Effect Cloud (UUID)
	public static final String BEAM_TARGET              = "BeamTarget";             // End Crystal (Comp, Pos)
	public static final String SHOW_BOTTOM              = "ShowBottom";             // End Crystal (Bool)
	public static final String MC_CUSTOM_DISPLAY        = "CustomDisplayTile";      // Minecart (Bool)
	public static final String MC_DISPLAY_TITLE         = "DisplayTile";            // Minecart (Str) -> Block
	public static final String MC_DISPLAY_DATA          = "DisplayData";            // Minecart (Int)
	public static final String MC_DISPLAY_OFFSET        = "DisplayOffset";          // Minecart (Int)
	public static final String MC_TNT_FUSE              = "TNTFuse";                // TNT Minecart (Int)
	public static final String MC_FURNACE_PUSH_X        = "PushX";                  // Furnace Minecart (Double)
	public static final String MC_FURNACE_PUSH_Z        = "PushZ";                  // Furnace Minecart (Double)
	public static final String MC_FURNACE_FUEL          = "Fuel";                   // Furnace Minecart (Short)
	public static final String MC_HOPPER_ENABLED        = "Enabled";                // Hopper Minecart (Bool)
	public static final String FALLING_BLOCK            = "Block";                  // FB (Str) -> Block
	public static final String FALLING_DATA             = "Data";                   // FB (Byte)
	public static final String FALLING_TIME             = "Time";                   // FB (Int)
	public static final String FALLING_DROP_ITEM        = "DropItem";               // FB (Bool)
	public static final String FALLING_HURT_ENT         = "HurtEntities";           // FB (Bool)
	public static final String FALLING_HURT_AMT         = "FallHurtAmount";         // FB (Float)
	public static final String FALLING_HURT_MAX         = "FallHurtMax";            // FB (Int)
	public static final String TILE_ENT_DATA            = "TileEntityData";         // FB (Compound) -> TE
	public static final String SH_BUL_STEPS             = "Steps";                  // SH BUL (Int)
	public static final String SH_BUL_TXD               = "TXD";                    // SH BUL (Double)
	public static final String SH_BUL_TYD               = "TYD";                    // SH BUL (Double)
	public static final String SH_BUL_TZD               = "TZD";                    // SH BUL (Double)
	public static final String SH_BUL_DIRECTION         = "Dir";                    // SH BUL (Int)
	public static final String SH_BUL_OWNER             = "Owner";                  // SH BUL (Compound)
	public static final String SH_BUL_OWNER_POS_X       = "X";                      // SH BUL (Owner, Int)
	public static final String SH_BUL_OWNER_POS_Y       = "Y";                      // SH BUL (Owner, Int)
	public static final String SH_BUL_OWNER_POS_Z       = "Z";                      // SH BUL (Owner, Int)
	public static final String SH_BUL_TARGET            = "Target";                 // SH BUL (Compound)
	public static final String SH_BUL_TARGET_POS_X      = "X";                      // SH BUL (Target, Int)
	public static final String SH_BUL_TARGET_POS_Y      = "Y";                      // SH BUL (Target, Int)
	public static final String SH_BUL_TARGET_POS_Z      = "Z";                      // SH BUL (Target, Int)
	public static final String FIREWORKS_LIFE           = "Life";                   // FW (Int)
	public static final String FIREWORKS_LIFE_TIME      = "LifeTime";               // FW (Int)
	public static final String FIREWORKS_ITEM           = "FireworksItem";          // FW (Compound) -> ItemStack
	public static final String TYPE                     = "Type";                   // Boat (Str)
	public static final String PROJ_TILE_X              = "xTile";                  // Arrow, Projectile (Int)
	public static final String PROJ_TILE_Y              = "yTile";                  // Arrow, Projectile (Int)
	public static final String PROJ_TILE_Z              = "zTile";                  // Arrow, Projectile (Int)
	public static final String PROJ_IN_TILE             = "inTile";                 // Arrow, Projectile (Str)
	public static final String PROJ_SHAKE               = "shake";                  // Arrow, Projectile (Byte)
	public static final String PROJ_IN_GROUND           = "inGround";               // Arrow, Projectile (Byte)
	public static final String PROJ_POTION              = "Potion";                 // Potion (Compound) -> ItemStack
	public static final String ARROW_LIFE               = "life";                   // Arrow (Short)
	public static final String ARROW_IN_DATA            = "inData";                 // Arrow (Byte)
	public static final String ARROW_DAMAGE             = "damage";                 // Arrow (Double)
	public static final String ARROW_PICKUP             = "pickup";                 // Arrow (Byte)
	public static final String ARROW_PLAYER             = "player";                 // Arrow (Bool)
	public static final String ARROW_CRIT               = "crit";                   // Arrow (Bool)
	public static final String ARROW_DURATION           = "Duration";               // Arrow, Spectral (Int)
	public static final String ARROW_POTION             = "Potion";                 // Arrow, Tipped (Str)
	public static final String ARROW_COLOR              = "Color";                  // Arrow, Tipped (Int)
	public static final String ARROW_EFFECTS            = "CustomPotionEffects";    // Arrow, Tipped (List, Comp) -> PotionEffect
	public static final String EXP_VALUE                = "Value";                  // EXP Orb (Short)
	public static final String EFF_AGE                  = "Age";                    // Eff Cloud (Int)
	public static final String EFF_DURATION             = "Duration";               // Eff Cloud (Int)
	public static final String EFF_WAIT_TIME            = "WaitTime";               // Eff Cloud (Int)
	public static final String EFF_RE_APP_DELAY         = "ReapplicationDelay";     // Eff Cloud (Int)
	public static final String EFF_DURATION_ON_USE      = "DurationOnUse";          // Eff Cloud (Int)
	public static final String EFF_RADIUS_ON_USE        = "RadiusOnUse";            // Eff Cloud (Float)
	public static final String EFF_RADIUS_TICK          = "RadiusPerTick";          // Eff Cloud (Float)
	public static final String EFF_RADIUS               = "Radius";                 // Eff Cloud (Float)
	public static final String EFF_PARTICLE             = "Particle";               // Eff Cloud (Str) -> ParticleType
	public static final String EFF_PARTICLE_1           = "ParticleParam1";         // Eff Cloud (Int)
	public static final String EFF_PARTICLE_2           = "ParticleParam2";         // Eff Cloud (Int)
	public static final String EFF_COLOR                = "Color";                  // Eff Cloud (Int)
	public static final String EFF_POTION_TYPE          = "Potion";                 // Eff Cloud (Str) -> PotionType
	public static final String EFF_EFFECTS              = "Effects";                // Eff Cloud (List, Comp) -> PotionEffect
	public static final String EFFECT_ID                = "Id";                     // [Base] PotionEffect (Byte)
	public static final String EFFECT_AMPLIFIER         = "Amplifier";              // [Base] PotionEffect (Byte)
	public static final String EFFECT_DURATION          = "Duration";               // [Base] PotionEffect (Int)
	public static final String EFFECT_AMBIENT           = "Ambient";                // [Base] PotionEffect (Bool)
	public static final String EFFECT_SHOW_PART         = "ShowParticles";          // [Base] PotionEffect (Bool)
	public static final String FACING_2                 = "Facing";                 // Hanging (Byte)
	public static final String TILE_X                   = "TileX";                  // Hanging (Int) -> Pos
	public static final String TILE_Y                   = "TileY";                  // Hanging (Int) -> Pos
	public static final String TILE_Z                   = "TileZ";                  // Hanging (Int) -> Pos
	public static final String ITEM_ROTATION            = "ItemRotation";           // Item Frame (Byte)
	public static final String ITEM_DROP_CHANCE         = "ItemDropChance";         // Item Frame (Float)
	public static final String PAINTING_TYPE            = "Motive";                 // Painting (Str)
	public static final String EXPLOSION_POWER          = "ExplosionPower";         // Large Fireball, Ghast (Int)
	public static final String HEALTH                   = "Health";                 // [LivingBase] (Float)
	public static final String HURT_TIME                = "HurtTime";               // [LivingBase] (Short)
	public static final String HURT_BY_TS               = "HurtByTimestamp";        // [LivingBase] (Int)
	public static final String DEATH_TIME               = "DeathTime";              // [LivingBase] (Short)
	public static final String ABSORB_AMT               = "AbsorptionAmount";       // [LivingBase] (Float)
	public static final String ATTRIBUTES               = "Attributes";             // [LivingBase] (List, Comp) --
	public static final String ATTRIB_NAME              = "Name";                   // [LivingBase] Attrib (Str) -> AttribInstance
	public static final String ATTRIB_BASE              = "Base";                   // [LivingBase] AttribInstance (Double)
	public static final String ATTRIB_MODIFIERS         = "Modifiers";              // [LivingBase] AttribInstance (List, Comp) -> AttribModifier
	public static final String MODIFIER_UUID            = "UUID";                   // [LivingBase] AttribModifier (UUID)
	public static final String MODIFIER_AMOUNT          = "Amount";                 // [LivingBase] AttribModifier (Double)
	public static final String ACTIVE_EFFECTS           = "ActiveEffects";          // [LivingBase] (List, Comp) -> PotionEffect
	public static final String FALL_FLYING              = "FallFlying";             // [LivingBase] (Bool)
	public static final String TEAM                     = "Team";                   // [LivingBase] (Str)
	public static final String ARMOR_ITEMS              = "ArmorItems";             // AS, Living (List, Comp) -> ItemStack
	public static final String HAND_ITEMS               = "HandItems";              // AS, Living (List, Comp) -> ItemStack
	public static final String INVISIBLE                = "Invisible";              // AS (Bool)
	public static final String AS_SMALL                 = "Small";                  // AS (Bool)
	public static final String AS_SHOW_ARMS             = "ShowArms";               // AS (Bool)
	public static final String AS_DISABLED_SLOTS        = "DisabledSlots";          // AS (Int)
	public static final String AS_NO_BASE_PLATE         = "NoBasePlate";            // AS (Bool)
	public static final String AS_MARKER                = "Marker";                 // AS (Bool)
	public static final String AS_POSE                  = "Pose";                   // AS (Compound)
	public static final String AS_POSE_HEAD             = "Head";                   // AS (List, Float) [x y z]
	public static final String AS_POSE_BODY             = "Body";                   // AS (List, Float) [x y z]
	public static final String AS_POSE_L_ARM            = "LeftArm";                // AS (List, Float) [x y z]
	public static final String AS_POSE_R_ARM            = "RightArm";               // AS (List, Float) [x y z]
	public static final String AS_POSE_L_LEG            = "LeftLeg";                // AS (List, Float) [x y z]
	public static final String AS_POSE_R_LEG            = "RightLeg";               // AS (List, Float) [x y z]
	public static final String CAN_PICKUP_LOOT          = "CanPickUpLoot";          // Living (Bool)
	public static final String PERSISTENCE              = "PersistenceRequired";    // Living (Bool)
	public static final String ARMOR_DROP_CHANCES       = "ArmorDropChances";       // Living (List, Float)
	public static final String HAND_DROP_CHANCES        = "HandDropChances";        // Living (List, Float)
	public static final String LEASHED                  = "Leashed";                // Living (Bool)
	public static final String LEASH                    = "Leash";                  // Living (Compound)
	public static final String LEFT_HANDED              = "LeftHanded";             // Living (Bool)
	public static final String DEATH_LOOT               = "DeathLootTable";         // Living (Str)
	public static final String DEATH_LOOT_SEED          = "DeathLootTableSeed";     // Living (Long)
	public static final String NO_AI                    = "NoAI";                   // Living (Bool)
	public static final String BAT_FLAGS                = "BatFlags";               // Bat (Byte)
	public static final String DRAGON_PHASE             = "DragonPhase";            // Dragon (Int)
	public static final String SIZE                     = "Size";                   // Slime (Int)
	public static final String WAS_ON_GROUND            = "wasOnGround";            // Slime (Bool)
	public static final String PLAYER_CREATED           = "PlayerCreated";          // Iron Golem (Bool)
	public static final String PUMPKIN                  = "Pumpkin";                // Snow Golem (Bool)
	public static final String SHULKER_ATTACH_FACE      = "AttachFace";             // Shulker (Byte)
	public static final String SHULKER_PEEK             = "Peek";                   // Shulker (Byte)
	public static final String SHULKER_APX              = "APX";                    // Shulker (Int)
	public static final String SHULKER_APY              = "APY";                    // Shulker (Int)
	public static final String SHULKER_APZ              = "APZ";                    // Shulker (Int)
	public static final String EXPLOSION_RADIUS         = "ExplosionRadius";        // Creeper (Byte)
	public static final String IGNITED                  = "ignited";                // Creeper (Bool)
	public static final String IS_BABY                  = "IsBaby";                 // Zombie (Bool)
	public static final String CAN_BREAK_DOORS          = "CanBreakDoors";          // Zombie (Bool)
	public static final String ANGER                    = "Anger";                  // Pig Zombie (Short)
	public static final String HURT_BY                  = "HurtBy";                 // Pig Zombie (Str) --> UUID
	public static final String PROFESSION               = "Profession";             // Zombie Villager, Villager (Int)
	public static final String ZOMBIE_CONVERSION        = "ConversionTime";         // Zombie Villager (Int)
	public static final String CONVERSION_PLAYER        = "ConversionPlayer";       // Zombie Villager (UUID)
	public static final String JOHNNY                   = "Johnny";                 // Vindicator (Bool)
	public static final String SPELL_TICKS              = "SpellTicks";             // Spell Caster (Int)
	public static final String CARRIED                  = "carried";                // Enderman (Short)
	public static final String CARRIED_DATA             = "carriedData";            // Enderman (Short)
	public static final String LIFE_TIME                = "Lifetime";               // Endermite (Int)
	public static final String PLAYER_SPAWNED           = "PlayerSpawned";          // Endermite (Bool)
	public static final String INVUL_TIME               = "Invul";                  // Wither (Int)
	public static final String LIFE_TICKS               = "LifeTicks";              // Vex (Int)
	public static final String BOUND_X                  = "BoundX";                 // Vex (Int)
	public static final String BOUND_Y                  = "BoundY";                 // Vex (Int)
	public static final String BOUND_Z                  = "BoundZ";                 // Vex (Int)
	public static final String GROWING_AGE              = "Age";                    // Agable (Int)
	public static final String FORCED_AGE               = "ForcedAge";              // Agable (Int)
	public static final String RICHES                   = "Riches";                 // Villager (Int)
	public static final String CAREER                   = "Career";                 // Villager (Int)
	public static final String CAREER_LEVEL             = "CareerLevel";            // Villager (Int)
	public static final String WILLING                  = "Willing";                // Villager (Bool)
	public static final String TRADE_OFFERS             = "Offers";                 // Villager (Comp) --> Recipes
	public static final String TRADE_RECIPES            = "Recipes";                // Villager (List, Comp) --> MerchantRecipe
	public static final String TRADE_BUY                = "buy";                    // MerchantRecipe (Comp) --> ItemStack
	public static final String TRADE_SELL               = "sell";                   // MerchantRecipe (Comp) --> ItemStack
	public static final String TRADE_BUY_B              = "buyB";                   // MerchantRecipe (Comp) --> ItemStack
	public static final String TRADE_USES               = "uses";                   // MerchantRecipe (Int)
	public static final String TRADE_MAX_USES           = "maxUses";                // MerchantRecipe (Int)
	public static final String TRADE_REWARD_EXP         = "rewardExp";              // MerchantRecipe (Bool)
	public static final String IN_LOVE                  = "InLove";                 // Animal (Int)
	public static final String LOVE_CAUSE               = "LoveCause";              // Animal (UUID)
	public static final String SHEARED                  = "Sheared";                // Sheep (Bool)
	public static final String SHEEP_COLOR              = "Color";                  // Sheep (Byte)
	public static final String SADDLED                  = "Saddle";                 // Pig (Bool)
	public static final String CHICKEN_JOCKEY           = "IsChickenJockey";        // Chicken (Bool)
	public static final String EGG_LAY_TIME             = "EggLayTime";             // Chicken (Int)
	public static final String RABBIT_TYPE              = "RabbitType";             // Rabbit (Int)
	public static final String MORE_CARROT_TICKS        = "MoreCarrotTicks";        // Rabbit (Int)
	public static final String TAMABLE_OWNER            = "OwnerUUID";              // Tamable (Str) --> UUID
	public static final String SITTING                  = "Sitting";                // Tamable (Bool)
	public static final String OCELOT_TYPE              = "CatType";                // Ocelot (Int)
	public static final String ANGRY                    = "Angry";                  // Wolf (Bool)
	public static final String COLLAR_COLOR             = "CollarColor";            // Wolf (Byte) --> DyeColor
	public static final String VARIANT                  = "Variant";                // Parrot, Horse, Llama (Int)
	public static final String EATING_HAY               = "EatingHaystack";         // AbstractHorse (Bool)
	public static final String HORSE_BRED               = "Bred";                   // AbstractHorse (Bool)
	public static final String HORSE_TEMPER             = "Temper";                 // AbstractHorse (Int)
	public static final String HORSE_TAME               = "Tame";                   // AbstractHorse (Bool)
	public static final String SADDLE                   = "SaddleItem";             // AbstractHorse (Compound) -> ItemStack (Inv Slot 0)
	public static final String SKELETON_TRAP            = "SkeletonTrap";           // Skeleton Horse (Bool)
	public static final String SKELETON_TRAP_TIME       = "SkeletonTrapTime";       // Skeleton Horse (Int)
	public static final String HORSE_ARMOR              = "ArmorItem";              // Horse (Compound) -> ItemStack (Inv Slot 1)
	public static final String CHESTED_HORSE            = "ChestedHorse";           // AbstractChestedHorse (Bool)
	public static final String STRENGTH                 = "Strength";               // Llama (Int)
	public static final String LLAMA_DECOR              = "DecorItem";              // Llama (Comp) -> ItemStack (Inv Slot 1)

	// Player [Base]
	public static final String DATA_VERSION             = "DataVersion";                // Int (Schema ID)
	public static final String SEL_ITEM_SLOT            = "SelectedItemSlot";           // Int
	public static final String SLEEPING                 = "Sleeping";                   // Bool
	public static final String SLEEP_TIMER              = "SleepTimer";                 // Short
	public static final String EXP_PROGRESS             = "XpP";                        // Float
	public static final String EXP_LEVEL                = "XpLevel";                    // Int
	public static final String EXP_TOTAL                = "XpTotal";                    // Int
	public static final String EXP_SEED                 = "XpSeed";                     // Int
	public static final String SCORE                    = "Score";                      // Int
	public static final String SPAWN_X                  = "SpawnX";                     // Int
	public static final String SPAWN_Y                  = "SpawnY";                     // Int
	public static final String SPAWN_Z                  = "SpawnZ";                     // Int
	public static final String SPAWN_FORCED             = "SpawnForced";                // Bool
	public static final String FOOD_LEVEL               = "foodLevel";                  // Int
	public static final String FOOD_TIMER               = "foodTickTimer";              // Int
	public static final String FOOD_SATURATION          = "foodSaturationLevel";        // Float
	public static final String FOOD_EXHAUSTION          = "foodExhaustionLevel";        // Float
	public static final String ABILITIES                = "abilities";                  // Compound -->
	public static final String ABL_INVULNERABLE         = "invulnerable";               // Bool
	public static final String ABL_FLYING               = "flying";                     // Bool
	public static final String ABL_MAY_FLY              = "mayfly";                     // Bool
	public static final String ABL_INST_BUILD           = "instabuild";                 // Bool
	public static final String ABL_FLY_SPEED            = "flySpeed";                   // Float
	public static final String ABL_WALK_SPEED           = "walkSpeed";                  // Float
	public static final String ABL_MAY_BUILD            = "mayBuild";                   // Bool
	public static final String ENDER_ITEMS              = "EnderItems";                 // List, Comp -> Slotted ItemStacks
	public static final String LEFT_SHOULDER            = "ShoulderEntityLeft";         // Comp -> Entity
	public static final String RIGHT_SHOULDER           = "ShoulderEntityRight";        // Comp -> Entity

	// Server Player
	public static final String GAME_TYPE                = "playerGameType";             // Int
	public static final String SEEN_CREDITS             = "seenCredits";                // Bool
	public static final String NETHER_POSITION          = "enteredNetherPosition";      // Comp --> [x y z]
	public static final String NETHER_POS_X             = "x";                          // Int
	public static final String NETHER_POS_Y             = "y";                          // Int
	public static final String NETHER_POS_Z             = "z";                          // Int
	public static final String ROOT_VEHICLE             = "RootVehicle";                // Comp -->
	public static final String ROOT_ENTITY              = "Entity";                     // Comp --> Entity
	public static final String ROOT_ATTACH              = "Attach";                     // UUID
	public static final String RECIPE_BOOK              = "recipeBook";                 // Compound -->
	public static final String RB_IS_GUI_OPEN           = "isGuiOpen";                  // Bool
	public static final String RB_IS_FIL_CRAFT          = "isFilteringCraftable";       // Bool
	public static final String RECIPES                  = "recipes";                    // List, String --> Recipe

	// Other/Newer Tags (There are tons more not listed possibly)
	// 1.13.x ?
	public static final String ORG_GOT_FISH             = "GotFish";                    // Dolphin
	public static final String ORG_CAN_FIND_TREASURE    = "CanFindTreasure";
	public static final String ORG_TREASURE_X           = "TreasurePosX";
	public static final String ORG_TREASURE_Y           = "TreasurePosY";
	public static final String ORG_TREASURE_Z           = "TreasurePosZ";
	public static final String ORG_MOISTNESS            = "Moistness";
	public static final String ORG_DROWNED_CONVERSION   = "DrownedConversionTime";      // Drowned
	public static final String ORG_IN_WATER             = "InWaterTime";
	public static final String ORG_PHANTOM_AX           = "AX";                         // Phantom
	public static final String ORG_PHANTOM_AY           = "AY";
	public static final String ORG_PHANTOM_AZ           = "AZ";
	public static final String ORG_PHANTOM_SIZE         = "Size";
	public static final String ORG_HOME_POS_X           = "HomePosX";                   // Turtle
	public static final String ORG_HOME_POS_Y           = "HomePosY";
	public static final String ORG_HOME_POS_Z           = "HomePosZ";
	public static final String ORG_TRAVEL_POS_X         = "TravelPosX";
	public static final String ORG_TRAVEL_POS_Y         = "TravelPosY";
	public static final String ORG_TRAVEL_POS_Z         = "TravelPosZ";
	public static final String ORG_HAS_EGG              = "HasEgg";
	// 1.14.x ?
	public static final String ORG_TYPE                 = "type";                       // Villager
	public static final String ORG_VILLAGER_DATA        = "VillagerData";
	public static final String ORG_VILLAGER_PROFESSION  = "profession";
	public static final String ORG_MAIN_GENE            = "MainGene";
	public static final String ORG_HIDDEN_GENE          = "HiddenGene";
	public static final String ORG_TRADE_SP_PRICE       = "specialPrice";
	public static final String ORG_TRADE_DEMAND         = "demand";
	public static final String ORG_TRADE_PRICE_MUL      = "priceMultiplier";
	public static final String ORG_TRADE_XP             = "xp";
	// 1.15.x ?
	public static final String ORG_BEES                 = "Bees";                       // Bees
	public static final String ORG_BOOK                 = "Book";                       // Lectern
	public static final String ORG_PAGE                 = "Page";
	public static final String ORG_RECIPES_USED         = "RecipesUsed";
	public static final String ORG_EXP_COUNT            = "Count";
	public static final String ORG_DISPLAY_STATE        = "DisplayState";               // AbstractMinecartEntity
	public static final String ORG_BLOCK_STATE          = "BlockStateTag";
	public static final String ORG_TICKS_FROZEN         = "TicksFrozen";
	public static final String ORG_HAS_VISUAL_FIRE      = "HasVisualFire";
	public static final String ORG_FLIPPED_ROTATION     = "FlippedRotation";
	public static final String ORG_HAS_TICKED           = "HasTicked";
	public static final String ORG_FALLING_BLOCK_STATE  = "BlockState";
	public static final String ORG_FALLING_TE_DATA      = "TileEntityData";
	public static final String ORG_BRAIN                = "Brain";
	public static final String ORG_ITEM_FIXED           = "Fixed";
	public static final String ORG_BUCKET_VARIANT       = "BucketVariantTag";
	public static final String ORG_ENCHANTMENTS         = "Enchantments";
	// 1.17.x ?
	public static final String ORG_STRAY_CONVERSION     = "StrayConversionTime";
	// 1.18.x ?
	// 1.19.x ?
	// 1.20.x ?
	public static final String NEW_FRONT_TEXT           = "front_text";                 // Sign
	public static final String NEW_BACK_TEXT            = "back_text";
	public static final String NEW_SIGN_MESSAGES        = "messages";
	public static final String NEW_SIGN_FILTERED        = "filtered_messages";
	public static final String NEW_SIGN_COLOR           = "color";
	public static final String NEW_SIGN_GLOW            = "has_glowing_text";
	public static final String NEW_NOTE                 = "note_block_sound";
	// 24w09a/1.20.5+ (Data Components)
	public static final String NEW_COMPONENTS           = "components";
	public static final String NEW_COUNT                = "count";
	public static final String NEW_BEES                 = "bees";
	public static final String NEW_SKULL_PROFILE        = "profile";
	public static final String NEW_SKULL_CUSTOM_NAME    = "custom_name";
	public static final String NEW_SKULL_PROPERTIES     = "properties";
	public static final String NEW_SKULL_NAME           = "name";
	public static final String NEW_SKULL_VALUE          = "value";
	public static final String NEW_SKULL_SIGNATURE      = "signature";
	public static final String NEW_TAGS                 = "tags";
	public static final String NEW_MAP_ID               = "map";
	public static final String NEW_ITEM                 = "item";
	public static final String NEW_SLEEPING_POS         = "sleeping_pos";
	public static final String NEW_FLOWER               = "flower_pos";
	public static final String NEW_EXIT                 = "exit_portal";
	public static final String NEW_WAXED                = "is_waxed";
	public static final String NEW_NEXT_WEATHER_AGE     = "next_weather_age";
	public static final String NEW_WEATHER_STATE        = "weather_state";
	public static final String NEW_VIBRATION            = "last_vibration_frequency";
	public static final String NEW_LISTENER             = "listener";
	public static final String NEW_PRIMARY_EFFECT       = "primary_effect";
	public static final String NEW_SECONDARY_EFFECT     = "secondary_effect";
	public static final String NEW_DISABLED_SLOTS       = "disabled_slots";
	public static final String NEW_MEMORIES             = "memories";
	public static final String NEW_CUSTOM_DATA          = "data";
	// 24w18a?/1.21+ (Attributes / Enchantments)
	public static final String NEW_ATTRIB               = "attributes";
	public static final String NEW_BODY_ARMOR           = "body_armor_item";
	// 1.21.2+ (RecipeBook)
	public static final String NEW_DISPLAYED            = "toBeDisplayed";
	// 1.21.4-pre2 (AbstractFurnaces)
	public static final String NEW_COOK_TIME_SPENT      = "cooking_time_spent";
	public static final String NEW_COOK_TIME_TOTAL      = "cooking_total_time";
	public static final String NEW_BURN_TIME            = "lit_time_remaining";
	public static final String NEW_BURN_TIME_TOTAL      = "lit_total_time";
	// 25w03a/1.21.5+ (Equipment Data Components / New tags / Entity Variants)
	public static final String NEW_EQUIPMENT            = "equipment";
	public static final String NEW_ANIMAL_ARMOR         = "body";
	public static final String NEW_SADDLE               = "saddle";
	public static final String NEW_FACING               = "facing";
	public static final String NEW_FALL_DISTANCE        = "fall_distance";
	public static final String NEW_TNT_FUSE             = "fuse";                       // TNT
	public static final String NEW_TNT_BLOCK_STATE      = "block_state";
	public static final String NEW_EXPLOSION_POWER      = "explosion_power";
	public static final String NEW_EXPLOSION_SPEED_FACT = "explosion_speed_factor";
	public static final String NEW_BEAM_TARGET          = "beam_target";                // EndCrystalEntity
	public static final String NEW_ATTACHED_BLOCK_POS   = "block_pos";
	public static final String NEW_SOUND_VARIANT        = "sound_variant";
	public static final String NEW_EFFECTS              = "active_effects";
	public static final String NEW_VARIANT              = "variant";
	public static final String NEW_CUSTOM_PARTICLE      = "custom_particle";            // AreaEffectCloudEntity
	public static final String NEW_POTION_CONTENTS      = "potion_contents";
	public static final String NEW_POTION_DURATION      = "potion_duration_scale";
	// 1.21.6+
	public static final String NEW_LEASH                = "leash";
	public static final String NEW_HOME_RADIUS          = "home_radius";                // MobEntity
	public static final String NEW_HOME_POS             = "home_pos";
	public static final String NEW_OMINOUS_TIMER        = "spawn_item_after_ticks";
	public static final String NEW_LOCATOR_ICON         = "locator_bar_icon";
}
